# Generated by Django 2.2.7 on 2019-11-26 06:28

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='chart_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
