# Generated by Django 2.2.7 on 2019-11-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191126_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='chart_title',
        ),
    ]
