# Generated by Django 2.2.7 on 2019-11-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_chart_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='content',
            new_name='contenty',
        ),
    ]
