# Generated by Django 2.2.7 on 2019-11-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191128_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='content',
            new_name='content_s',
        ),
    ]
