# Generated by Django 2.2.7 on 2019-11-29 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191128_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='content_s',
            new_name='content',
        ),
    ]
